### ISSUE TITLE
Inconsistant field type used

### ISSUE THREAD

**Issue by sachaw** [asbiin/laravel-webauthn#125]
the default users table has a data type of bigIncrements and the webauthn table references this as an unsignedInteger and results in an error

```
SQLSTATE[HY000]: General error: 1005 Can't create table `main`.`webauthn_keys` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `webauthn_keys` add constraint `webauthn_keys_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade)
```

As outlined here

https://stackoverflow.com/questions/40863517/laravel-errno-150-foreign-key-constraint-is-incorrectly-formed

**Comment by sachaw** [comment]
I changed it to
```
$table->bigInteger('user_id')->unsigned();
```

**Comment by asbiin** [comment]
Thanks for the review! This is fixed.
