### ISSUE TITLE
Can we have some example? 

### ISSUE THREAD

**Issue by Cherry-Pie** [asbiin/laravel-webauthn#22]
It will help a lot. I would really appreciate if you provide it.
And I guess it will help others too.

**Comment by asbiin** [comment]
Completely agree.
I'm implementing it in Monica, here: https://github.com/monicahq/monica/pull/2570

**Comment by asbiin** [comment]
You will find some documentation on the [README](https://github.com/asbiin/laravel-webauthn/blob/master/README.md) file, and [here](https://github.com/asbiin/laravel-webauthn-example) it's an example of a new Laravel application.

**Comment by asbiin** [comment]
Let me know if it's clear enough like this.
