### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by ajpwade** [asbiin/laravel-webauthn#236]
The current [constraint in composer.json](https://github.com/asbiin/laravel-webauthn/blob/070cd590682a15543fc27646bbcbcb9803d7940c/composer.json#L24) doesn't allow Laravel 7 even though in the README it says:

> This package supports Laravel 5.8 and newer, and has been tested with php 7.2 and newer versions.

This is a direct copy of #157 @asbiin can we make this more automatic or at least limit what is said in the Readme so that we aren't expecting it to work in newer versions?

**Comment by asbiin** [comment]
Well, what is said on the readme was true at the moment it was written!
I don't know how to extend the list of supported version with composer. For now it's "^5.8 || ^6.0", but I'll have to extend it for each major laravel version ...

**Comment by ajpwade** [comment]
Changing it to "laravel/framework": ">5.8" would allow it to install on any version greater than 5.8 although i assume ymmv depending on if it works with newer versions.  Could always list approved versions as 5.8 and 6 in the readme.
