### ISSUE TITLE
Laravel 7.6 compatibility?

### ISSUE THREAD

**Issue by rbourque** [asbiin/laravel-webauthn#270]
My composer.json contains these lines
   "asbiin/laravel-webauthn": "^0.7.0",
   "laravel/framework": "^7.6",

$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v7.6.1
    - Conclusion: don't install laravel/framework v7.6.0
    - Conclusion: don't install laravel/framework v7.5.2
    - Conclusion: don't install laravel/framework v7.5.1
    - Conclusion: don't install laravel/framework v7.5.0
    - Conclusion: don't install laravel/framework v7.4.0
    - Conclusion: don't install laravel/framework v7.3.0
    - Conclusion: don't install laravel/framework v7.2.2
    - Conclusion: don't install laravel/framework v7.2.1
    - Conclusion: don't install laravel/framework v7.2.0
    - Conclusion: don't install laravel/framework v7.1.3
    - Conclusion: don't install laravel/framework v7.1.2
    - Conclusion: don't install laravel/framework v7.1.1
    - Conclusion: don't install laravel/framework v7.1.0
    - Conclusion: don't install laravel/framework v7.0.8
    - Conclusion: don't install laravel/framework v7.0.7
    - Conclusion: don't install laravel/framework v7.0.6
    - Conclusion: don't install laravel/framework v7.0.5
    - Conclusion: don't install laravel/framework v7.0.4
    - Conclusion: don't install laravel/framework v7.0.3
    - Conclusion: don't install laravel/framework v7.0.2
    - Installation request for asbiin/laravel-webauthn ^0.7.0 -> satisfiable by asbiin/laravel-webauthn[0.7.0].
    - Conclusion: don't install laravel/framework v7.0.1
    - Conclusion: don't install laravel/framework v7.0.0
    - asbiin/laravel-webauthn 0.7.0 requires laravel/framework ^5.8 || ^6.0 -> satisfiable by laravel/framework[5.8.x-dev, 6.x-dev].
    - Can only install one of: laravel/framework[7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[7.x-dev, 6.x-dev].
    - Installation request for laravel/framework ^7.0 -> satisfiable by laravel/framework[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.2.0, v7.2.1, v7.2.2, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1].

**Comment by r4v** [comment]
same here: laravel 7.6.1:

`
Using version ^0.8.0 for asbiin/laravel-webauthn
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for asbiin/laravel-webauthn ^0.8.0 -> satisfiable by asbiin/laravel-webauthn[0.8.0].
    - Conclusion: remove ramsey/uuid 4.0.1
    - Conclusion: don't install ramsey/uuid 4.0.1
    - asbiin/laravel-webauthn 0.8.0 requires web-auth/webauthn-lib ^3.0 -> satisfiable by web-auth/webauthn-lib[v3.0.0, v3.0.1, v3.0.2, v3.0.x-dev, v3.1.0, v3.1.1, v3.1.x-dev].
    - web-auth/webauthn-lib v3.0.0 requires ramsey/uuid ^3.8 -> satisfiable by ramsey/uuid[3.8.0, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.x-dev].
    - web-auth/webauthn-lib v3.0.1 requires ramsey/uuid ^3.8 -> satisfiable by ramsey/uuid[3.8.0, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.x-dev].
    - web-auth/webauthn-lib v3.0.2 requires ramsey/uuid ^3.8 -> satisfiable by ramsey/uuid[3.8.0, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.x-dev].
    - web-auth/webauthn-lib v3.0.x-dev requires ramsey/uuid ^3.8 -> satisfiable by ramsey/uuid[3.8.0, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.x-dev].
    - web-auth/webauthn-lib v3.1.0 requires ramsey/uuid ^3.8 -> satisfiable by ramsey/uuid[3.8.0, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.x-dev].
    - web-auth/webauthn-lib v3.1.1 requires ramsey/uuid ^3.8 -> satisfiable by ramsey/uuid[3.8.0, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.x-dev].
    - web-auth/webauthn-lib v3.1.x-dev requires ramsey/uuid ^3.8 -> satisfiable by ramsey/uuid[3.8.0, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.x-dev].
    - Can only install one of: ramsey/uuid[3.8.0, 4.0.1].
    - Can only install one of: ramsey/uuid[3.9.0, 4.0.1].
    - Can only install one of: ramsey/uuid[3.9.1, 4.0.1].
    - Can only install one of: ramsey/uuid[3.9.2, 4.0.1].
    - Can only install one of: ramsey/uuid[3.9.3, 4.0.1].
    - Can only install one of: ramsey/uuid[3.x-dev, 4.0.1].
    - Installation request for ramsey/uuid (locked at 4.0.1) -> satisfiable by ramsey/uuid[4.0.1].

`

**Comment by rbourque** [comment]
Weird, today I did a composer install and everything installed without conflicts...   Maybe it was something wrong in the composer database?

**Comment by asbiin** [comment]
Well, composer dependencies are sometimes creappy.
Anyway, glad you could make it.
