### ISSUE TITLE
Authentication Exception thrown when calling any of the provided routes

### ISSUE THREAD

**Issue by Matt561** [asbiin/laravel-webauthn#301]
When the user is not yet authenticated calling any of the webauthn routes (ex: register) throws an authentication exception. I've manually authenticated the user with `Auth::login()` to get the webauthn routes to work correctly but this completely negates the usage of webauthn.

Perhaps I am missing something, the examples are unclear.  Any help you can provide is appreciated.

**Comment by MarkIvanowich** [comment]
This package does not replace the standard user authentication. (ie, doesn't replace using a password, instead it acts as 2FA on the prebundled Auth package)

I think you want the parent package https://github.com/web-auth/webauthn-framework and create your own Auth fork.
