### ISSUE TITLE
Apple TouchID support

### ISSUE THREAD

**Issue by CWallenberg** [asbiin/laravel-webauthn#335]
Hi.
I have a user in one of my websites that are not able to use his iPhone's TouchID feature for webAuthn authencation.
Is there a possibility to have it added? Or if support already exists, am i missing something?
Thanks

**Comment by Chew** [comment]
This is natively supported in webauthn.
![image](https://user-images.githubusercontent.com/8278263/135007880-b0970df0-9c16-4b8c-917e-07fb2844964c.png)

**Comment by CWallenberg** [comment]
That explains why they couldn't use WebAuthn.
Thanks
