### ISSUE TITLE
Compatibility of this package

### ISSUE THREAD

**Issue by DurandSacha** [asbiin/laravel-webauthn#344]
What is the compatibility of this module? It seems that mobile browsers are not eligible for the webauthn protocol ...

`'the user agent does not support public key credentials'`
or 
`Your browser dosen't currently support webauthn` ( chrome for android ).

Is there a way to configure a package, or increase the configuration of laravel to extend compatibility with chrome for android in particular?

android browser is supposed to accept this technology ([canIuse](https://caniuse.com/?search=webauthn) )

**Comment by asbiin** [comment]
This module rely on [web-auth/webauthn-framework](https://github.com/web-auth/webauthn-framework), and webauthn browser support.

A lot of browser currently support webauthn.
You can see
- https://developers.yubico.com/WebAuthn/WebAuthn_Browser_Support/
- https://caniuse.com/webauthn

In any case, if you use this module, it should be better to let the user use webauthn as an optional 2FA or login process...
