### ISSUE TITLE
Support for Laravel 8 as an API?

### ISSUE THREAD

**Issue by zaidysf** [asbiin/laravel-webauthn#388]
So, currently I have 1 running Laravel (v8) app.
Is this latest version still support for Laravel 8? or any other version can I use for Laravel 8?

If not, Is that possible to use this as an API?
I tried to build the [sample app](https://github.com/asbiin/laravel-webauthn-example) (it worked) but I have no idea how to integrate with my Laravel 8 app.
Thank you!

**Comment by asbiin** [comment]
Hi @zaidysf 
Laravel 8 is supported with version 2.0.1 of laravel-webauthn. However the latest version needs Laravel 9
