### ISSUE TITLE
Dynamic model used instead of forcing to use User

### ISSUE THREAD

**Issue by zaidysf** [asbiin/laravel-webauthn#390]
Any possibility to dynamically change default auth model from User to another model since Laravel support dynamic auth model?
e.g :
In my case, I am using `Staffs` (not _Users_) table which has `staff_id` (not _user_id_) as the primary key.

**Comment by asbiin** [comment]
I did not test it, but I guess you can do it.
This package is not tied to the `User` model.
You'll just have to adapt the migration script for you, and use `Staffs` as model provider in `config/auth.php` config file. Note that it must implement `Illuminate\Contracts\Auth\Access\Authorizable` which is a Laravel constraint.
