### ISSUE TITLE
is there a way to use 2.0.1 with sanctum?

### ISSUE THREAD

**Issue by ChaerilM** [asbiin/laravel-webauthn#414]
`$request->session()` will not work on sanctum, is there another way to do it ?

**Comment by asbiin** [comment]
I would really recommend you to upgrade to version 3.x.
Also I don't know any way of using v2.0.1 with sanctum, but v3 *is* working with it.

**Comment by ChaerilM** [comment]
i'm using L8, and can't upgrade it since the boss likes 'if it ain't broke, don't fix it'. in the end we dropped it since implementing and testing to the front end would take a longer time and does not fit in our tight deadline.
