### ISSUE TITLE
Demo application stopped working

### ISSUE THREAD

**Issue by emilas44** [asbiin/laravel-webauthn#429]
https://webauthn.asbin.net

there was some change and the buttons now point to non https links, therefore this error message

```
Mixed Content: The page at 'https://webauthn.asbin.net/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://webauthn.asbin.net/register'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by asbiin** [comment]
Thank you, it has been fixed with https://github.com/asbiin/laravel-webauthn-example/pull/661
