### ISSUE TITLE
Uncaught TypeError: e is undefined

### ISSUE THREAD

**Issue by syntafin** [asbiin/laravel-webauthn#433]
After figuring out how to integrate it, with the example application, I am now facing the following problem:

> Uncaught TypeError: e is undefined

The affected code is this here:

```js
!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t:"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.WebAuthn=t:e.WebAuthn=t}(this, WebAuthn);
```

especially this: ``e.WebAuthn``

Depending on my google search, this is a jQuery function, that means this package needs jQuery?

**Comment by asbiin** [comment]
You should switch to [`@simplewebauthn/browser`](https://www.npmjs.com/package/@simplewebauthn/browser) which is fully supported.

**Comment by syntafin** [comment]
I don't understand how a standalone solution should help with the problem that a jQuery function is referred here?
