### ISSUE TITLE
Key Specification without a key length

### ISSUE THREAD

**Issue by grafst** [asbiin/laravel-webauthn#434]
php artisan migrate

   INFO  Running migrations.

  2019_03_29_163611_add_webauthn ................................... 36ms FAIL

   Illuminate\Database\QueryException

  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'credentialId' used in key specification without a key length (Connection: mysql, SQL: alter table `webauthn_keys` add index `webauthn_keys_credentialid_index`(`credentialId`))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:793
    789▕         // If an exception occurs when attempting to run a query, we'll format the error
    790▕         // message to include the bindings with SQL, which will make this exception a
    791▕         // lot more helpful to the developer instead of just the database's errors.
    792▕         catch (Exception $e) {
  ➜ 793▕             throw new QueryException(
    794▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    795▕             );
    796▕         }
    797▕     }

      +9 vendor frames
  10  database/migrations/2019_03_29_163611_add_webauthn.php:16
      Illuminate\Support\Facades\Facade::__callStatic("create")

      +24 vendor frames
  35  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by asbiin** [comment]
fixed by #431
