### ISSUE TITLE
The relying party ID is not a registrable domain suffix of, nor equal to the current domain

### ISSUE THREAD

**Issue by markuskoehler** [asbiin/laravel-webauthn#470]
Hello,

more of a questions than of a bug, I suppose. But as a webauthn beginner I cannot figure out where it comes from or how to solve it.

I am getting the error "The relying party ID is not a registrable domain suffix of, nor equal to the current domain." despite having exposed my Laravel App via Beyondcode Expose to a domain like https://mw...eq.sharedwithexpose.com/ - I have also adjusted the APP_URL, ASSET_URL and vite config. But I cannot figure out where to check or set the RP ID in this implementation.

Can you help please?

**Comment by asbiin** [comment]
The `RpId` comes from the `request()->host()`.
If this one is not properly set, then you probably don't have the right proxy configuration.
See https://laravel.com/docs/11.x/requests#configuring-trusted-proxies to configure trusted proxies.

In any cases, this is more a configuration issue on your application than an actual issue on this package, hence I'll close this issue. Don't hesitate to look for more help on stackoverflow or any other forum!
