### ISSUE TITLE
Can't change view response to Inertia

### ISSUE THREAD

**Issue by JanniGrabe** [asbiin/laravel-webauthn#480]
I tried to copy the example from the readme but I get the following exception:

`Symfony\Component\HttpFoundation\Response::setContent(): Argument #1 ($content) must be of type ?string, Inertia\Response given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php on line 72`

README:
> You can easily change the view responses with the Webauthn service.
> For instance, call Webauthn::loginViewResponseUsing in your AppServiceProvider:
> ```
> use LaravelWebauthn\Services\Webauthn;
> 
> class AppServiceProvider extends ServiceProvider
> {
>     public function register()
>     {
>         Webauthn::loginViewResponseUsing(LoginViewResponse::class);
>     }
> }
>```
> With a LoginViewResponse class:
> ```
> use LaravelWebauthn\Http\Responses\LoginViewResponse as LoginViewResponseBase;
> 
> class LoginViewResponse extends LoginViewResponseBase
> {
>     public function toResponse($request)
>     {
>         $publicKey = $this->publicKeyRequest($request);
> 
>         return Inertia::render('Webauthn/WebauthnLogin', [
>             'publicKey' => $publicKey
>         ]);
>     }
> }
>```

I guess right now it's just working with blade views? Also, $this->publicKeyRequest does not exist, though that's not the cause for this problem.

**Comment by asbiin** [comment]
You're right, it misses the `toResponse()` call, like that:
```
use LaravelWebauthn\Http\Responses\LoginViewResponse as LoginViewResponseBase;

class LoginViewResponse extends LoginViewResponseBase
{
    public function toResponse($request)
    {
        $publicKey = $this->publicKeyRequest($request);

        return Inertia::render('Webauthn/WebauthnLogin', [
            'publicKey' => $publicKey
        ])->toResponse($request);
    }
}
```

See my example app: https://github.com/asbiin/laravel-webauthn-example/blob/main/app/Http/Responses/LoginViewResponse.php
